# exportar_kan_cpp.py moved to src/export/export_kan_cpp.py
import os
import torch
import numpy as np

def export_kan_to_cpp(model, output_path="firmware/generated_headers/kan_model.h", class_names=None, use_progmem=True):
    model.eval()
    raw_width = model.width
    width = []
    for w in raw_width:
        if isinstance(w, (list, tuple)):
            width.append(int(w[0]))
        else:
            width.append(int(w))
    depth = model.depth
    k     = model.k
    layers_data = []
    for l_idx in range(depth):
        layer = model.act_fun[l_idx]
        n_in  = int(layer.in_dim)
        n_out = int(layer.out_dim)
        grid       = layer.grid.detach().cpu().float().numpy()
        coef       = layer.coef.detach().cpu().float().numpy()
        scale_base = layer.scale_base.detach().cpu().float().numpy()
        scale_sp   = layer.scale_sp.detach().cpu().float().numpy()
        mask       = layer.mask.detach().cpu().float().numpy()
        nb = model.node_bias[l_idx]
        if nb is not None:
            node_bias = nb.detach().cpu().float().numpy().flatten()
        else:
            node_bias = np.zeros(n_out, dtype=np.float32)
        n_knots = grid.shape[1]
        n_coef  = coef.shape[2]
        layers_data.append({'n_in':n_in,'n_out':n_out,'n_knots':n_knots,'n_coef':n_coef,'grid':grid,'coef':coef,'scale_base':scale_base,'scale_sp':scale_sp,'mask':mask,'node_bias':node_bias})
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    pg = "PROGMEM " if use_progmem else ""
    def fmt_row(arr):
        return ", ".join(f"{float(v):.7f}f" for v in arr)
    lines = []
    lines += ["// kan_model.h — generated by export_kan_cpp.py", "#ifndef KAN_MODEL_H", "#define KAN_MODEL_H", "#include <cmath>", "#include <pgmspace.h>"]
    lines += [f"#define KAN_DEPTH     {depth}", f"#define KAN_K         {k}", f"#define KAN_N_IN      {width[0]}", f"#define KAN_N_CLASSES {width[-1]}", ""]
    if class_names:
        lines.append("// Classes: " + ", ".join(f"{i}={c}" for i,c in enumerate(class_names)))
        lines.append("")
    for l_idx, ld in enumerate(layers_data):
        n_in = ld['n_in']; n_out = ld['n_out']; n_knots = ld['n_knots']; n_coef = ld['n_coef']
        lines.append(f"// Layer {l_idx} ({n_in} -> {n_out})")
        lines.append(f"const float {pg}L{l_idx}_GRID[{n_in}][{n_knots}] = {{")
        for i in range(n_in):
            lines.append(f"    /* in={i:2d} */ {{ {fmt_row(ld['grid'][i])} }},")
        lines.append("};\n")
        lines.append(f"const float {pg}L{l_idx}_COEF[{n_in}][{n_out}][{n_coef}] = {{")
        for i in range(n_in):
            lines.append(f"    /* in={i:2d} */ {{")
            for j in range(n_out):
                lines.append(f"        /* out={j:2d} */ {{ {fmt_row(ld['coef'][i, j])} }},")
            lines.append("    },")
        lines.append("};\n")
        lines.append(f"const float {pg}L{l_idx}_SCALE_BASE[{n_in}][{n_out}] = {{")
        for i in range(n_in):
            lines.append(f"    /* in={i:2d} */ {{ {fmt_row(ld['scale_base'][i])} }},")
        lines.append("};\n")
        lines.append(f"const float {pg}L{l_idx}_SCALE_SP[{n_in}][{n_out}] = {{")
        for i in range(n_in):
            lines.append(f"    /* in={i:2d} */ {{ {fmt_row(ld['scale_sp'][i])} }},")
        lines.append("};\n")
        lines.append(f"const float {pg}L{l_idx}_MASK[{n_in}][{n_out}] = {{")
        for i in range(n_in):
            lines.append(f"    /* in={i:2d} */ {{ {fmt_row(ld['mask'][i])} }},")
        lines.append("};\n")
        lines.append(f"const float {pg}L{l_idx}_BIAS[{n_out}] = {{ {fmt_row(ld['node_bias'])} }};\n")
    # Minimal De Boor and wrapper omitted for brevity — user has original in repo
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    return output_path


def verify_export(model, X_val_t, y_val_enc, n_samples=200):
    # Reuse original verify_export logic from repo if needed
    print('verify_export placeholder — use original script for full check')
    return None
